# Generated by Django 5.2.15 on 2026-08-31 00:00

from django.db import migrations, models
from django.db.models import Min


def align_existing_project_access(apps, schema_editor):
    workspace_member = apps.get_model("db", "WorkspaceMember")
    workspace_member_invite = apps.get_model("db", "WorkspaceMemberInvite")
    project = apps.get_model("db", "Project")
    project_member = apps.get_model("db", "ProjectMember")
    project_user_property = apps.get_model("db", "ProjectUserProperty")

    for member in workspace_member.objects.all().iterator():
        default_project_role = 20 if member.role == 20 else 5 if member.role == 5 else 15

        if not member.is_active:
            project_access_scope = "none"
        elif member.role == 20:
            project_access_scope = "all"
            public_projects = project.objects.filter(
                workspace_id=member.workspace_id,
                network=2,
                archived_at__isnull=True,
            ).only("id", "workspace_id")
            for public_project in public_projects.iterator():
                membership = project_member.objects.filter(
                    project_id=public_project.id,
                    member_id=member.member_id,
                ).first()
                if membership is None:
                    project_member.objects.create(
                        project_id=public_project.id,
                        workspace_id=member.workspace_id,
                        member_id=member.member_id,
                        role=20,
                        is_active=True,
                    )
                else:
                    project_member.objects.filter(pk=membership.pk).update(
                        workspace_id=member.workspace_id,
                        role=20,
                        is_active=True,
                    )

                if not project_user_property.objects.filter(
                    project_id=public_project.id,
                    user_id=member.member_id,
                ).exists():
                    minimum_sort_order = project_user_property.objects.filter(
                        workspace_id=member.workspace_id,
                        user_id=member.member_id,
                    ).aggregate(value=Min("sort_order"))["value"]
                    project_user_property.objects.create(
                        project_id=public_project.id,
                        workspace_id=member.workspace_id,
                        user_id=member.member_id,
                        sort_order=(minimum_sort_order - 10000 if minimum_sort_order is not None else 65535),
                    )
        else:
            has_active_project = project_member.objects.filter(
                workspace_id=member.workspace_id,
                member_id=member.member_id,
                is_active=True,
                project__archived_at__isnull=True,
            ).exists()
            project_access_scope = "selected" if has_active_project else "none"

        workspace_member.objects.filter(pk=member.pk).update(
            project_access_scope=project_access_scope,
            default_project_role=default_project_role,
        )

    workspace_member_invite.objects.filter(role=20).update(
        project_access_scope="all",
        default_project_role=20,
        project_ids=[],
    )
    workspace_member_invite.objects.filter(role=15).update(
        project_access_scope="none",
        default_project_role=15,
        project_ids=[],
    )
    workspace_member_invite.objects.filter(role=5).update(
        project_access_scope="none",
        default_project_role=5,
        project_ids=[],
    )


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0122_alter_draftissue_assignees_alter_issue_assignees_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspacemember",
            name="default_project_role",
            field=models.PositiveSmallIntegerField(
                choices=[(20, "Admin"), (15, "Member"), (5, "Guest")],
                default=15,
            ),
        ),
        migrations.AddField(
            model_name="workspacemember",
            name="project_access_scope",
            field=models.CharField(
                choices=[
                    ("all", "All current and future public projects"),
                    ("selected", "Selected projects"),
                    ("none", "No projects"),
                ],
                default="selected",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="workspacememberinvite",
            name="default_project_role",
            field=models.PositiveSmallIntegerField(
                choices=[(20, "Admin"), (15, "Member"), (5, "Guest")],
                default=15,
            ),
        ),
        migrations.AddField(
            model_name="workspacememberinvite",
            name="project_access_scope",
            field=models.CharField(
                choices=[
                    ("all", "All current and future public projects"),
                    ("selected", "Selected projects"),
                    ("none", "No projects"),
                ],
                default="none",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="workspacememberinvite",
            name="project_ids",
            field=models.JSONField(default=list),
        ),
        migrations.RunPython(
            align_existing_project_access,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
