# Generated by Django 5.2.15 on 2026-08-30 11:37

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("db", "0122_alter_draftissue_assignees_alter_issue_assignees_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudioDecision",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("question", models.TextField(max_length=2000)),
                ("context", models.TextField(blank=True, default="", max_length=5000)),
                ("recommendation", models.TextField(blank=True, default="", max_length=5000)),
                ("final_decision", models.TextField(blank=True, default="", max_length=5000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("NEEDS_DECISION", "Needs decision"),
                            ("DECIDED", "Decided"),
                            ("REVISIT", "Revisit"),
                            ("REVERSED", "Reversed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=24,
                    ),
                ),
                ("due_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_%(class)s",
                        to="db.project",
                    ),
                ),
                (
                    "proposer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="proposed_studio_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_%(class)s",
                        to="db.workspace",
                    ),
                ),
            ],
            options={"db_table": "studio_decisions", "ordering": ("due_at", "-created_at")},
        ),
        migrations.CreateModel(
            name="StudioRisk",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("PRODUCT", "Product"),
                            ("TECHNICAL", "Technical"),
                            ("DELIVERY", "Delivery"),
                            ("LEGAL", "Legal"),
                            ("FINANCIAL", "Financial"),
                            ("MARKET", "Market"),
                            ("OPERATIONS", "Operations"),
                            ("SECURITY", "Security"),
                        ],
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True, default="", max_length=5000)),
                (
                    "probability",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                (
                    "impact",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("score", models.PositiveSmallIntegerField(editable=False)),
                ("is_blocker", models.BooleanField(db_index=True, default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("MITIGATING", "Mitigating"),
                            ("MONITORING", "Monitoring"),
                            ("ACCEPTED", "Accepted"),
                            ("CLOSED", "Closed"),
                        ],
                        default="OPEN",
                        max_length=16,
                    ),
                ),
                ("mitigation", models.TextField(blank=True, default="", max_length=5000)),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_studio_risks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_%(class)s",
                        to="db.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_%(class)s",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "studio_risks",
                "ordering": ("-score", "due_at", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="StudioProjectProfile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("IOS_APP", "iOS app"),
                            ("WECHAT_MINI_PROGRAM", "WeChat mini program"),
                            ("WEB_APP", "Web app"),
                            ("SERVICE", "Service"),
                            ("CONTENT", "Content"),
                            ("RESEARCH", "Research"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=32,
                    ),
                ),
                (
                    "portfolio_bucket",
                    models.CharField(
                        choices=[
                            ("FOCUS", "Focus"),
                            ("NEXT", "Next"),
                            ("INCUBATING", "Incubating"),
                            ("KEEP_ALIVE", "Keep alive"),
                            ("PAUSED", "Paused"),
                            ("ARCHIVED", "Archived"),
                        ],
                        db_index=True,
                        default="INCUBATING",
                        max_length=24,
                    ),
                ),
                (
                    "lifecycle_stage",
                    models.CharField(
                        choices=[
                            ("IDEA", "Idea"),
                            ("RESEARCH", "Research"),
                            ("VALIDATED", "Validated"),
                            ("DESIGN", "Design"),
                            ("BUILD", "Build"),
                            ("TEST", "Test"),
                            ("RELEASE_READY", "Release ready"),
                            ("LIVE", "Live"),
                            ("GROWTH", "Growth"),
                            ("MAINTENANCE", "Maintenance"),
                        ],
                        db_index=True,
                        default="IDEA",
                        max_length=24,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("P0", "P0"), ("P1", "P1"), ("P2", "P2"), ("P3", "P3")],
                        default="P2",
                        max_length=2,
                    ),
                ),
                ("focus_statement", models.CharField(blank=True, default="", max_length=300)),
                (
                    "expected_update_interval_days",
                    models.PositiveSmallIntegerField(
                        default=14,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(365),
                        ],
                    ),
                ),
                ("progress_expected_since", models.DateTimeField(blank=True, null=True)),
                ("last_meaningful_activity_at", models.DateTimeField(blank=True, null=True)),
                (
                    "manual_health",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ON_TRACK", "On track"),
                            ("AT_RISK", "At risk"),
                            ("BLOCKED", "Blocked"),
                            ("STALE", "Stale"),
                            ("PAUSED", "Paused"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("manual_health_reason", models.CharField(blank=True, max_length=500, null=True)),
                ("manual_health_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operated_studio_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_%(class)s",
                        to="db.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_%(class)s",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "studio_project_profiles",
                "ordering": ("project__name",),
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=("project",),
                        name="studio_profile_unique_active_project",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StudioRelease",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("version", models.CharField(max_length=40)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("INTERNAL", "Internal"),
                            ("TEST", "Test"),
                            ("BETA", "Beta"),
                            ("PRODUCTION", "Production"),
                        ],
                        default="INTERNAL",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Planned"),
                            ("SCOPING", "Scoping"),
                            ("BUILDING", "Building"),
                            ("QA", "QA"),
                            ("READY", "Ready"),
                            ("SUBMITTED", "Submitted"),
                            ("REVIEW", "Review"),
                            ("RELEASED", "Released"),
                            ("ROLLED_BACK", "Rolled back"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PLANNED",
                        max_length=16,
                    ),
                ),
                ("target_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("scope_summary", models.TextField(blank=True, default="", max_length=2000)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="studio_releases",
                        to="db.module",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_%(class)s",
                        to="db.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_%(class)s",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "studio_releases",
                "ordering": ("target_at", "-created_at"),
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=("project", "version"),
                        name="studio_release_unique_active_version",
                    )
                ],
            },
        ),
    ]

