# Generated by Django 5.2.15 on 2026-08-31 00:00

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _base_fields():
    return [
        ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
        ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
        ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
        (
            "id",
            models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        (
            "created_by",
            models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        (
            "updated_by",
            models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Last Modified By",
            ),
        ),
        (
            "project",
            models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_%(class)s",
                to="db.project",
            ),
        ),
        (
            "workspace",
            models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workspace_%(class)s",
                to="db.workspace",
            ),
        ),
    ]


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0122_alter_draftissue_assignees_alter_issue_assignees_and_more"),
        ("studio", "0002_governance"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudioFeedback",
            fields=_base_fields()
            + [
                ("title", models.CharField(max_length=160)),
                ("body", models.TextField(blank=True, default="", max_length=5000)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Manual"),
                            ("EMAIL", "Email"),
                            ("APP_STORE", "App Store"),
                            ("WECHAT", "WeChat"),
                            ("SOCIAL", "Social"),
                            ("SUPPORT", "Support"),
                            ("OTHER", "Other"),
                        ],
                        default="MANUAL",
                        max_length=16,
                    ),
                ),
                (
                    "sentiment",
                    models.CharField(
                        choices=[
                            ("POSITIVE", "Positive"),
                            ("NEUTRAL", "Neutral"),
                            ("NEGATIVE", "Negative"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=16,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("P0", "P0"), ("P1", "P1"), ("P2", "P2"), ("P3", "P3")],
                        default="P2",
                        max_length=2,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INBOX", "Inbox"),
                            ("TRIAGED", "Triaged"),
                            ("PLANNED", "Planned"),
                            ("RESOLVED", "Resolved"),
                            ("WONT_DO", "Won't do"),
                            ("DUPLICATE", "Duplicate"),
                        ],
                        db_index=True,
                        default="INBOX",
                        max_length=16,
                    ),
                ),
                ("category", models.CharField(blank=True, default="", max_length=64)),
                ("reporter_name", models.CharField(blank=True, default="", max_length=120)),
                ("source_url", models.CharField(blank=True, default="", max_length=500)),
                (
                    "linked_issue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="studio_feedback_links",
                        to="db.issue",
                    ),
                ),
            ],
            options={"db_table": "studio_feedback", "ordering": ("-created_at",)},
        ),
        migrations.CreateModel(
            name="StudioContentItem",
            fields=_base_fields()
            + [
                ("title", models.CharField(max_length=160)),
                ("brief", models.TextField(blank=True, default="", max_length=2000)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("WECHAT", "WeChat"),
                            ("X", "X"),
                            ("BLOG", "Blog"),
                            ("EMAIL", "Email"),
                            ("VIDEO", "Video"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IDEA", "Idea"),
                            ("DRAFT", "Draft"),
                            ("REVIEW", "Review"),
                            ("APPROVED", "Approved"),
                            ("SCHEDULED", "Scheduled"),
                            ("PUBLISHED", "Published"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="IDEA",
                        max_length=16,
                    ),
                ),
                ("planned_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("published_url", models.CharField(blank=True, default="", max_length=500)),
                ("notes", models.TextField(blank=True, default="", max_length=2000)),
                (
                    "linked_issue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="studio_content_links",
                        to="db.issue",
                    ),
                ),
            ],
            options={"db_table": "studio_content_items", "ordering": ("planned_at", "-created_at")},
        ),
        migrations.CreateModel(
            name="StudioRoutine",
            fields=_base_fields()
            + [
                ("name", models.CharField(max_length=160)),
                (
                    "cadence",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("MONTHLY", "Monthly"),
                            ("AD_HOC", "Ad hoc"),
                        ],
                        default="WEEKLY",
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("next_due_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="", max_length=2000)),
                (
                    "linked_issue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="studio_routine_links",
                        to="db.issue",
                    ),
                ),
            ],
            options={"db_table": "studio_routines", "ordering": ("name",)},
        ),
        migrations.CreateModel(
            name="StudioExperiment",
            fields=_base_fields()
            + [
                ("title", models.CharField(max_length=160)),
                ("hypothesis", models.TextField(blank=True, default="", max_length=2000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("STOPPED", "Stopped"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                ("start_at", models.DateTimeField(blank=True, null=True)),
                ("end_at", models.DateTimeField(blank=True, null=True)),
                ("result", models.TextField(blank=True, default="", max_length=5000)),
                ("conclusion", models.TextField(blank=True, default="", max_length=5000)),
                (
                    "linked_issue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="studio_experiment_links",
                        to="db.issue",
                    ),
                ),
            ],
            options={"db_table": "studio_experiments", "ordering": ("-created_at",)},
        ),
    ]
