# Generated by Django 5.2.15 on 2026-08-31 06:00

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _base_fields(project_required=True):
    fields = [
        ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
        ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
        ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
        (
            "id",
            models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        (
            "created_by",
            models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        (
            "updated_by",
            models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Last Modified By",
            ),
        ),
        (
            "workspace",
            models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workspace_%(class)s",
                to="db.workspace",
            ),
        ),
        (
            "project",
            models.ForeignKey(
                null=not project_required,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_%(class)s",
                to="db.project",
            ),
        ),
    ]
    return fields


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0122_alter_draftissue_assignees_alter_issue_assignees_and_more"),
        ("studio", "0003_operations"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudioMetricDefinition",
            fields=_base_fields(True)
            + [
                ("name", models.CharField(max_length=160)),
                ("key", models.CharField(max_length=64)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("COUNT", "Count"),
                            ("PERCENT", "Percent"),
                            ("CURRENCY", "Currency"),
                            ("DURATION", "Duration"),
                            ("SCORE", "Score"),
                            ("OTHER", "Other"),
                        ],
                        default="COUNT",
                        max_length=16,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("UP_IS_GOOD", "Up is good"),
                            ("DOWN_IS_GOOD", "Down is good"),
                            ("TARGET_RANGE", "Target range"),
                            ("NEUTRAL", "Neutral"),
                        ],
                        default="NEUTRAL",
                        max_length=16,
                    ),
                ),
                ("target_value", models.FloatField(blank=True, null=True)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("MONTHLY", "Monthly"),
                            ("AD_HOC", "Ad hoc"),
                        ],
                        default="WEEKLY",
                        max_length=16,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[("MANUAL", "Manual"), ("GITHUB", "GitHub"), ("CUSTOM", "Custom")],
                        default="MANUAL",
                        max_length=16,
                    ),
                ),
                ("is_core", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={"db_table": "studio_metric_definitions", "ordering": ("name",)},
        ),
        migrations.CreateModel(
            name="StudioMetricSnapshot",
            fields=_base_fields(True)
            + [
                ("captured_at", models.DateTimeField(db_index=True)),
                ("numeric_value", models.FloatField(blank=True, null=True)),
                ("text_value", models.CharField(blank=True, default="", max_length=160)),
                ("source", models.CharField(default="MANUAL", max_length=16)),
                ("note", models.CharField(blank=True, default="", max_length=500)),
                (
                    "metric_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="studio.studiometricdefinition",
                    ),
                ),
            ],
            options={"db_table": "studio_metric_snapshots", "ordering": ("captured_at",)},
        ),
        migrations.CreateModel(
            name="StudioWeeklyReview",
            fields=_base_fields(False)
            + [
                ("week_start", models.DateField(db_index=True)),
                ("retrospective", models.TextField(blank=True, default="", max_length=5000)),
                ("health_summary", models.TextField(blank=True, default="", max_length=5000)),
                ("focus", models.TextField(blank=True, default="", max_length=2000)),
                ("risks", models.TextField(blank=True, default="", max_length=2000)),
                ("next_steps", models.TextField(blank=True, default="", max_length=2000)),
            ],
            options={"db_table": "studio_weekly_reviews", "ordering": ("-week_start",)},
        ),
        migrations.AddConstraint(
            model_name="studiometricdefinition",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("project", "key"),
                name="studio_metric_unique_active_project_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="studioweeklyreview",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("workspace", "week_start"),
                name="studio_weekly_review_unique_active_week",
            ),
        ),
    ]
