# Generated by Django 5.2.15 on 2026-08-31 07:00

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _base_fields(project_null=False):
    return [
        ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
        ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
        ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
        (
            "id",
            models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        (
            "created_by",
            models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        (
            "updated_by",
            models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Last Modified By",
            ),
        ),
        (
            "workspace",
            models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workspace_%(class)s",
                to="db.workspace",
            ),
        ),
        (
            "project",
            models.ForeignKey(
                null=project_null,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_%(class)s",
                to="db.project",
            ),
        ),
    ]


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0122_alter_draftissue_assignees_alter_issue_assignees_and_more"),
        ("studio", "0004_cadence"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudioGithubBinding",
            fields=_base_fields()
            + [
                ("repository", models.CharField(blank=True, default="", max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_EXTERNAL_CREDENTIAL", "Pending external credential"),
                            ("CONNECTED", "Connected"),
                            ("DEGRADED", "Degraded"),
                        ],
                        db_index=True,
                        default="PENDING_EXTERNAL_CREDENTIAL",
                        max_length=32,
                    ),
                ),
                ("last_captured_at", models.DateTimeField(blank=True, null=True)),
                ("degraded_reason", models.CharField(blank=True, default="", max_length=500)),
            ],
            options={"db_table": "studio_github_bindings", "ordering": ("-updated_at",)},
        ),
        migrations.CreateModel(
            name="StudioGithubProjection",
            fields=_base_fields()
            + [
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("PULL_REQUEST", "Pull request"),
                            ("CI", "CI"),
                            ("RELEASE", "Release"),
                            ("LAST_COMMIT", "Last commit"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("external_id", models.CharField(db_index=True, max_length=80)),
                ("captured_at", models.DateTimeField(db_index=True)),
                ("title", models.CharField(blank=True, default="", max_length=300)),
                ("url", models.CharField(blank=True, default="", max_length=500)),
                ("payload", models.JSONField(blank=True, default=dict)),
            ],
            options={"db_table": "studio_github_projections", "ordering": ("-captured_at",)},
        ),
        migrations.CreateModel(
            name="StudioGithubDelivery",
            fields=_base_fields(project_null=True)
            + [
                ("delivery_id", models.CharField(db_index=True, max_length=80)),
                ("event", models.CharField(max_length=64)),
                ("processed_at", models.DateTimeField()),
            ],
            options={"db_table": "studio_github_deliveries", "ordering": ("-processed_at",)},
        ),
        migrations.AddConstraint(
            model_name="studiogithubbinding",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("project",),
                name="studio_github_binding_unique_active_project",
            ),
        ),
        migrations.AddConstraint(
            model_name="studiogithubprojection",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("project", "kind", "external_id"),
                name="studio_github_projection_unique_active_fact",
            ),
        ),
        migrations.AddConstraint(
            model_name="studiogithubdelivery",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("delivery_id",),
                name="studio_github_delivery_unique_active_id",
            ),
        ),
    ]
