# Copyright (c) 2023-present Plane Software, Inc. and contributors
# SPDX-License-Identifier: AGPL-3.0-only
# See the LICENSE file for details.

from django.urls import path

from plane.studio.views import (
    StudioDecisionDetailEndpoint,
    StudioDecisionListEndpoint,
    StudioPortfolioEndpoint,
    StudioProjectOverviewEndpoint,
    StudioProjectProfileEndpoint,
    StudioReleaseDetailEndpoint,
    StudioReleaseListEndpoint,
    StudioRiskDetailEndpoint,
    StudioRiskListEndpoint,
    StudioTodayEndpoint,
)
from plane.studio.views_governance import (
    StudioDecisionAcknowledgementListEndpoint,
    StudioDecisionAcknowledgementSelfEndpoint,
    StudioDecisionOptionDetailEndpoint,
    StudioDecisionOptionListEndpoint,
    StudioMilestoneDetailEndpoint,
    StudioMilestoneListEndpoint,
    StudioProjectEventListEndpoint,
    StudioReleaseChecklistItemEndpoint,
)
from plane.studio.views_operations import (
    StudioContentConvertEndpoint,
    StudioContentDetailEndpoint,
    StudioContentListEndpoint,
    StudioExperimentConvertEndpoint,
    StudioExperimentDetailEndpoint,
    StudioExperimentListEndpoint,
    StudioFeedbackConvertEndpoint,
    StudioFeedbackDetailEndpoint,
    StudioFeedbackListEndpoint,
    StudioOperationsEndpoint,
    StudioRoutineConvertEndpoint,
    StudioRoutineDetailEndpoint,
    StudioRoutineListEndpoint,
)

app_name = "studio"

urlpatterns = [
    path("workspaces/<str:slug>/today/", StudioTodayEndpoint.as_view(), name="today"),
    path("workspaces/<str:slug>/portfolio/", StudioPortfolioEndpoint.as_view(), name="portfolio"),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/overview/",
        StudioProjectOverviewEndpoint.as_view(),
        name="project-overview",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/profile/",
        StudioProjectProfileEndpoint.as_view(),
        name="project-profile",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/releases/",
        StudioReleaseListEndpoint.as_view(),
        name="release-list",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/releases/<uuid:pk>/",
        StudioReleaseDetailEndpoint.as_view(),
        name="release-detail",
    ),
    path(
        "workspaces/<str:slug>/decisions/",
        StudioDecisionListEndpoint.as_view(),
        name="decision-list",
    ),
    path(
        "workspaces/<str:slug>/decisions/<uuid:pk>/",
        StudioDecisionDetailEndpoint.as_view(),
        name="decision-detail",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/risks/",
        StudioRiskListEndpoint.as_view(),
        name="risk-list",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/risks/<uuid:pk>/",
        StudioRiskDetailEndpoint.as_view(),
        name="risk-detail",
    ),
    path(
        "workspaces/<str:slug>/decisions/<uuid:pk>/options/",
        StudioDecisionOptionListEndpoint.as_view(),
        name="decision-option-list",
    ),
    path(
        "workspaces/<str:slug>/decisions/<uuid:pk>/options/<uuid:option_id>/",
        StudioDecisionOptionDetailEndpoint.as_view(),
        name="decision-option-detail",
    ),
    path(
        "workspaces/<str:slug>/decisions/<uuid:pk>/acknowledgements/",
        StudioDecisionAcknowledgementListEndpoint.as_view(),
        name="decision-acknowledgement-list",
    ),
    path(
        "workspaces/<str:slug>/decisions/<uuid:pk>/acknowledgements/me/",
        StudioDecisionAcknowledgementSelfEndpoint.as_view(),
        name="decision-acknowledgement-self",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/milestones/",
        StudioMilestoneListEndpoint.as_view(),
        name="milestone-list",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/milestones/<uuid:pk>/",
        StudioMilestoneDetailEndpoint.as_view(),
        name="milestone-detail",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/releases/<uuid:pk>/checklist/<uuid:item_id>/",
        StudioReleaseChecklistItemEndpoint.as_view(),
        name="release-checklist-item",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/events/",
        StudioProjectEventListEndpoint.as_view(),
        name="project-event-list",
    ),
    path(
        "workspaces/<str:slug>/operations/",
        StudioOperationsEndpoint.as_view(),
        name="operations",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/feedback/",
        StudioFeedbackListEndpoint.as_view(),
        name="feedback-list",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/feedback/<uuid:pk>/",
        StudioFeedbackDetailEndpoint.as_view(),
        name="feedback-detail",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/feedback/<uuid:pk>/convert/",
        StudioFeedbackConvertEndpoint.as_view(),
        name="feedback-convert",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/content/",
        StudioContentListEndpoint.as_view(),
        name="content-list",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/content/<uuid:pk>/",
        StudioContentDetailEndpoint.as_view(),
        name="content-detail",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/content/<uuid:pk>/convert/",
        StudioContentConvertEndpoint.as_view(),
        name="content-convert",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/routines/",
        StudioRoutineListEndpoint.as_view(),
        name="routine-list",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/routines/<uuid:pk>/",
        StudioRoutineDetailEndpoint.as_view(),
        name="routine-detail",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/routines/<uuid:pk>/convert/",
        StudioRoutineConvertEndpoint.as_view(),
        name="routine-convert",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/experiments/",
        StudioExperimentListEndpoint.as_view(),
        name="experiment-list",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/experiments/<uuid:pk>/",
        StudioExperimentDetailEndpoint.as_view(),
        name="experiment-detail",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/experiments/<uuid:pk>/convert/",
        StudioExperimentConvertEndpoint.as_view(),
        name="experiment-convert",
    ),
]
